included:
  - Sources
  - Tests

excluded:
  - Sources/GeneratedAPI

disabled_rules:
  - trailing_whitespace
  - todo
  - nesting
  - function_body_length
  - type_body_length
  - file_length
  - cyclomatic_complexity

opt_in_rules:
  - empty_count
  - closure_spacing
  - force_unwrapping
  - implicitly_unwrapped_optional
  - overridden_super_call
  - redundant_nil_coalescing
  - vertical_whitespace_closing_braces

line_length:
  warning: 150
  error: 200

identifier_name:
  min_length: 1

type_name:
  min_length: 2
